package com.Lbins.TvApp.module;

import com.Lbins.TvApp.dao.AdObjDao;
import com.Lbins.TvApp.dao.DaoSession;
import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table AD_OBJ.
 */
public class AdObj {

    /** Not-null value. */
    private String mm_ad_id;
    private String mm_ad_url;
    private String mm_ad_pic;
    private String mm_ad_type;
    private String mm_ad_num;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AdObjDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AdObj() {
    }

    public AdObj(String mm_ad_id) {
        this.mm_ad_id = mm_ad_id;
    }

    public AdObj(String mm_ad_id, String mm_ad_url, String mm_ad_pic, String mm_ad_type, String mm_ad_num) {
        this.mm_ad_id = mm_ad_id;
        this.mm_ad_url = mm_ad_url;
        this.mm_ad_pic = mm_ad_pic;
        this.mm_ad_type = mm_ad_type;
        this.mm_ad_num = mm_ad_num;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAdObjDao() : null;
    }

    /** Not-null value. */
    public String getMm_ad_id() {
        return mm_ad_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_ad_id(String mm_ad_id) {
        this.mm_ad_id = mm_ad_id;
    }

    public String getMm_ad_url() {
        return mm_ad_url;
    }

    public void setMm_ad_url(String mm_ad_url) {
        this.mm_ad_url = mm_ad_url;
    }

    public String getMm_ad_pic() {
        return mm_ad_pic;
    }

    public void setMm_ad_pic(String mm_ad_pic) {
        this.mm_ad_pic = mm_ad_pic;
    }

    public String getMm_ad_type() {
        return mm_ad_type;
    }

    public void setMm_ad_type(String mm_ad_type) {
        this.mm_ad_type = mm_ad_type;
    }

    public String getMm_ad_num() {
        return mm_ad_num;
    }

    public void setMm_ad_num(String mm_ad_num) {
        this.mm_ad_num = mm_ad_num;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
