package com.Lbins.TvApp.module;

import com.Lbins.TvApp.dao.CityObjDao;
import com.Lbins.TvApp.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import java.io.Serializable;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table CITY_OBJ.
 */
public class CityObj implements Serializable{

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String cityID;
    /** Not-null value. */
    private String city;
    /** Not-null value. */
    private String father;
    /** Not-null value. */
    private String provinceName;
    /** Not-null value. */
    private String topnum;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CityObjDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CityObj() {
    }

    public CityObj(String id) {
        this.id = id;
    }

    public CityObj(String id, String cityID, String city, String father, String provinceName, String topnum) {
        this.id = id;
        this.cityID = cityID;
        this.city = city;
        this.father = father;
        this.provinceName = provinceName;
        this.topnum = topnum;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCityObjDao() : null;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCityID() {
        return cityID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityID(String cityID) {
        this.cityID = cityID;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getFather() {
        return father;
    }

    public void setFather(String father) {
        this.father = father;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getTopnum() {
        return topnum;
    }

    public void setTopnum(String topnum) {
        this.topnum = topnum;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
