package com.Lbins.TvApp.module;

import com.Lbins.TvApp.dao.DaoSession;
import com.Lbins.TvApp.dao.EmpDao;
import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table EMP.
 */
public class Emp {

    /** Not-null value. */
    private String hxusername;
    /** Not-null value. */
    private String mm_emp_mobile;
    /** Not-null value. */
    private String mm_emp_nickname;
    private String mm_emp_card;
    /** Not-null value. */
    private String mm_emp_password;
    /** Not-null value. */
    private String mm_emp_cover;
    private String mm_emp_company;
    private String mm_emp_provinceId;
    private String mm_emp_cityId;
    private String mm_emp_countryId;
    private String mm_emp_regtime;
    private String is_login;
    private String is_use;
    private String lat;
    private String lng;
    private String ischeck;
    private String is_upate_profile;
    private String userId;
    private String channelId;
    private String deviceType;
    private String mm_emp_email;
    private String mm_emp_sex;
    private String mm_emp_birthday;
    private String mm_emp_techang;
    private String mm_emp_xingqu;
    private String mm_emp_detail;
    private String guiren_card_num;
    private String mm_hangye_id;
    private String mm_emp_up_emp;
    private String provinceName;
    private String cityName;
    private String mm_hangye_name;
    private String areaName;
    private String top_number;
    private String mm_emp_weixin;
    private String mm_emp_qq;
    private String mm_emp_age;
    private String mm_emp_native;
    private String mm_emp_motto;
    /** Not-null value. */
    private String mm_emp_id;
    private String mm_emp_type;
    private String mm_emp_bg;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EmpDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Emp() {
    }

    public Emp(String hxusername) {
        this.hxusername = hxusername;
    }

    public Emp(String hxusername, String mm_emp_mobile, String mm_emp_nickname, String mm_emp_card, String mm_emp_password, String mm_emp_cover, String mm_emp_company, String mm_emp_provinceId, String mm_emp_cityId, String mm_emp_countryId, String mm_emp_regtime, String is_login, String is_use, String lat, String lng, String ischeck, String is_upate_profile, String userId, String channelId, String deviceType, String mm_emp_email, String mm_emp_sex, String mm_emp_birthday, String mm_emp_techang, String mm_emp_xingqu, String mm_emp_detail, String guiren_card_num, String mm_hangye_id, String mm_emp_up_emp, String provinceName, String cityName, String mm_hangye_name, String areaName, String top_number, String mm_emp_weixin, String mm_emp_qq, String mm_emp_age, String mm_emp_native, String mm_emp_motto, String mm_emp_id, String mm_emp_type, String mm_emp_bg) {
        this.hxusername = hxusername;
        this.mm_emp_mobile = mm_emp_mobile;
        this.mm_emp_nickname = mm_emp_nickname;
        this.mm_emp_card = mm_emp_card;
        this.mm_emp_password = mm_emp_password;
        this.mm_emp_cover = mm_emp_cover;
        this.mm_emp_company = mm_emp_company;
        this.mm_emp_provinceId = mm_emp_provinceId;
        this.mm_emp_cityId = mm_emp_cityId;
        this.mm_emp_countryId = mm_emp_countryId;
        this.mm_emp_regtime = mm_emp_regtime;
        this.is_login = is_login;
        this.is_use = is_use;
        this.lat = lat;
        this.lng = lng;
        this.ischeck = ischeck;
        this.is_upate_profile = is_upate_profile;
        this.userId = userId;
        this.channelId = channelId;
        this.deviceType = deviceType;
        this.mm_emp_email = mm_emp_email;
        this.mm_emp_sex = mm_emp_sex;
        this.mm_emp_birthday = mm_emp_birthday;
        this.mm_emp_techang = mm_emp_techang;
        this.mm_emp_xingqu = mm_emp_xingqu;
        this.mm_emp_detail = mm_emp_detail;
        this.guiren_card_num = guiren_card_num;
        this.mm_hangye_id = mm_hangye_id;
        this.mm_emp_up_emp = mm_emp_up_emp;
        this.provinceName = provinceName;
        this.cityName = cityName;
        this.mm_hangye_name = mm_hangye_name;
        this.areaName = areaName;
        this.top_number = top_number;
        this.mm_emp_weixin = mm_emp_weixin;
        this.mm_emp_qq = mm_emp_qq;
        this.mm_emp_age = mm_emp_age;
        this.mm_emp_native = mm_emp_native;
        this.mm_emp_motto = mm_emp_motto;
        this.mm_emp_id = mm_emp_id;
        this.mm_emp_type = mm_emp_type;
        this.mm_emp_bg = mm_emp_bg;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEmpDao() : null;
    }

    /** Not-null value. */
    public String getHxusername() {
        return hxusername;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHxusername(String hxusername) {
        this.hxusername = hxusername;
    }

    /** Not-null value. */
    public String getMm_emp_mobile() {
        return mm_emp_mobile;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_mobile(String mm_emp_mobile) {
        this.mm_emp_mobile = mm_emp_mobile;
    }

    /** Not-null value. */
    public String getMm_emp_nickname() {
        return mm_emp_nickname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_nickname(String mm_emp_nickname) {
        this.mm_emp_nickname = mm_emp_nickname;
    }

    public String getMm_emp_card() {
        return mm_emp_card;
    }

    public void setMm_emp_card(String mm_emp_card) {
        this.mm_emp_card = mm_emp_card;
    }

    /** Not-null value. */
    public String getMm_emp_password() {
        return mm_emp_password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_password(String mm_emp_password) {
        this.mm_emp_password = mm_emp_password;
    }

    /** Not-null value. */
    public String getMm_emp_cover() {
        return mm_emp_cover;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_cover(String mm_emp_cover) {
        this.mm_emp_cover = mm_emp_cover;
    }

    public String getMm_emp_company() {
        return mm_emp_company;
    }

    public void setMm_emp_company(String mm_emp_company) {
        this.mm_emp_company = mm_emp_company;
    }

    public String getMm_emp_provinceId() {
        return mm_emp_provinceId;
    }

    public void setMm_emp_provinceId(String mm_emp_provinceId) {
        this.mm_emp_provinceId = mm_emp_provinceId;
    }

    public String getMm_emp_cityId() {
        return mm_emp_cityId;
    }

    public void setMm_emp_cityId(String mm_emp_cityId) {
        this.mm_emp_cityId = mm_emp_cityId;
    }

    public String getMm_emp_countryId() {
        return mm_emp_countryId;
    }

    public void setMm_emp_countryId(String mm_emp_countryId) {
        this.mm_emp_countryId = mm_emp_countryId;
    }

    public String getMm_emp_regtime() {
        return mm_emp_regtime;
    }

    public void setMm_emp_regtime(String mm_emp_regtime) {
        this.mm_emp_regtime = mm_emp_regtime;
    }

    public String getIs_login() {
        return is_login;
    }

    public void setIs_login(String is_login) {
        this.is_login = is_login;
    }

    public String getIs_use() {
        return is_use;
    }

    public void setIs_use(String is_use) {
        this.is_use = is_use;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getIscheck() {
        return ischeck;
    }

    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }

    public String getIs_upate_profile() {
        return is_upate_profile;
    }

    public void setIs_upate_profile(String is_upate_profile) {
        this.is_upate_profile = is_upate_profile;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getMm_emp_email() {
        return mm_emp_email;
    }

    public void setMm_emp_email(String mm_emp_email) {
        this.mm_emp_email = mm_emp_email;
    }

    public String getMm_emp_sex() {
        return mm_emp_sex;
    }

    public void setMm_emp_sex(String mm_emp_sex) {
        this.mm_emp_sex = mm_emp_sex;
    }

    public String getMm_emp_birthday() {
        return mm_emp_birthday;
    }

    public void setMm_emp_birthday(String mm_emp_birthday) {
        this.mm_emp_birthday = mm_emp_birthday;
    }

    public String getMm_emp_techang() {
        return mm_emp_techang;
    }

    public void setMm_emp_techang(String mm_emp_techang) {
        this.mm_emp_techang = mm_emp_techang;
    }

    public String getMm_emp_xingqu() {
        return mm_emp_xingqu;
    }

    public void setMm_emp_xingqu(String mm_emp_xingqu) {
        this.mm_emp_xingqu = mm_emp_xingqu;
    }

    public String getMm_emp_detail() {
        return mm_emp_detail;
    }

    public void setMm_emp_detail(String mm_emp_detail) {
        this.mm_emp_detail = mm_emp_detail;
    }

    public String getGuiren_card_num() {
        return guiren_card_num;
    }

    public void setGuiren_card_num(String guiren_card_num) {
        this.guiren_card_num = guiren_card_num;
    }

    public String getMm_hangye_id() {
        return mm_hangye_id;
    }

    public void setMm_hangye_id(String mm_hangye_id) {
        this.mm_hangye_id = mm_hangye_id;
    }

    public String getMm_emp_up_emp() {
        return mm_emp_up_emp;
    }

    public void setMm_emp_up_emp(String mm_emp_up_emp) {
        this.mm_emp_up_emp = mm_emp_up_emp;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getMm_hangye_name() {
        return mm_hangye_name;
    }

    public void setMm_hangye_name(String mm_hangye_name) {
        this.mm_hangye_name = mm_hangye_name;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getTop_number() {
        return top_number;
    }

    public void setTop_number(String top_number) {
        this.top_number = top_number;
    }

    public String getMm_emp_weixin() {
        return mm_emp_weixin;
    }

    public void setMm_emp_weixin(String mm_emp_weixin) {
        this.mm_emp_weixin = mm_emp_weixin;
    }

    public String getMm_emp_qq() {
        return mm_emp_qq;
    }

    public void setMm_emp_qq(String mm_emp_qq) {
        this.mm_emp_qq = mm_emp_qq;
    }

    public String getMm_emp_age() {
        return mm_emp_age;
    }

    public void setMm_emp_age(String mm_emp_age) {
        this.mm_emp_age = mm_emp_age;
    }

    public String getMm_emp_native() {
        return mm_emp_native;
    }

    public void setMm_emp_native(String mm_emp_native) {
        this.mm_emp_native = mm_emp_native;
    }

    public String getMm_emp_motto() {
        return mm_emp_motto;
    }

    public void setMm_emp_motto(String mm_emp_motto) {
        this.mm_emp_motto = mm_emp_motto;
    }

    /** Not-null value. */
    public String getMm_emp_id() {
        return mm_emp_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_id(String mm_emp_id) {
        this.mm_emp_id = mm_emp_id;
    }

    public String getMm_emp_type() {
        return mm_emp_type;
    }

    public void setMm_emp_type(String mm_emp_type) {
        this.mm_emp_type = mm_emp_type;
    }

    public String getMm_emp_bg() {
        return mm_emp_bg;
    }

    public void setMm_emp_bg(String mm_emp_bg) {
        this.mm_emp_bg = mm_emp_bg;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
