package com.Lbins.TvApp.module;

import com.Lbins.TvApp.dao.DaoSession;
import com.Lbins.TvApp.dao.XixunObjDao;
import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table XIXUN_OBJ.
 */
public class XixunObj {

    /** Not-null value. */
    private String guiren_xixun_id;
    /** Not-null value. */
    private String guiren_xixun_title;
    /** Not-null value. */
    private String mm_emp_id;
    private String dateline;
    private String mm_emp_nickname;
    private String mm_emp_cover;
    private String mm_hangye_name;
    private String mm_emp_sex;
    private String mm_emp_mobile;
    private String lat;
    private String lng;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient XixunObjDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public XixunObj() {
    }

    public XixunObj(String guiren_xixun_id) {
        this.guiren_xixun_id = guiren_xixun_id;
    }

    public XixunObj(String guiren_xixun_id, String guiren_xixun_title, String mm_emp_id, String dateline, String mm_emp_nickname, String mm_emp_cover, String mm_hangye_name, String mm_emp_sex, String mm_emp_mobile, String lat, String lng) {
        this.guiren_xixun_id = guiren_xixun_id;
        this.guiren_xixun_title = guiren_xixun_title;
        this.mm_emp_id = mm_emp_id;
        this.dateline = dateline;
        this.mm_emp_nickname = mm_emp_nickname;
        this.mm_emp_cover = mm_emp_cover;
        this.mm_hangye_name = mm_hangye_name;
        this.mm_emp_sex = mm_emp_sex;
        this.mm_emp_mobile = mm_emp_mobile;
        this.lat = lat;
        this.lng = lng;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getXixunObjDao() : null;
    }

    /** Not-null value. */
    public String getGuiren_xixun_id() {
        return guiren_xixun_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuiren_xixun_id(String guiren_xixun_id) {
        this.guiren_xixun_id = guiren_xixun_id;
    }

    /** Not-null value. */
    public String getGuiren_xixun_title() {
        return guiren_xixun_title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuiren_xixun_title(String guiren_xixun_title) {
        this.guiren_xixun_title = guiren_xixun_title;
    }

    /** Not-null value. */
    public String getMm_emp_id() {
        return mm_emp_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMm_emp_id(String mm_emp_id) {
        this.mm_emp_id = mm_emp_id;
    }

    public String getDateline() {
        return dateline;
    }

    public void setDateline(String dateline) {
        this.dateline = dateline;
    }

    public String getMm_emp_nickname() {
        return mm_emp_nickname;
    }

    public void setMm_emp_nickname(String mm_emp_nickname) {
        this.mm_emp_nickname = mm_emp_nickname;
    }

    public String getMm_emp_cover() {
        return mm_emp_cover;
    }

    public void setMm_emp_cover(String mm_emp_cover) {
        this.mm_emp_cover = mm_emp_cover;
    }

    public String getMm_hangye_name() {
        return mm_hangye_name;
    }

    public void setMm_hangye_name(String mm_hangye_name) {
        this.mm_hangye_name = mm_hangye_name;
    }

    public String getMm_emp_sex() {
        return mm_emp_sex;
    }

    public void setMm_emp_sex(String mm_emp_sex) {
        this.mm_emp_sex = mm_emp_sex;
    }

    public String getMm_emp_mobile() {
        return mm_emp_mobile;
    }

    public void setMm_emp_mobile(String mm_emp_mobile) {
        this.mm_emp_mobile = mm_emp_mobile;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
